GET http://10.10.100.10:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMCwibmFtZSI6IkRvciIsInVzZXJuYW1lIjoiZG9yZG9yMSIsImVtYWlsIjoiZG9yMTAwQGRsb3AuY29tIiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTcwODUwMzAwMywiZXhwIjoxNzA4NTAzMTAzfQ.wnef2eE10f5h2hJRASOeWG-QTPgCeZTIEShzLkKu0Cw

### Post
POST http://10.10.100.10:3000/users
content-type: application/json

{
  "heb_name" : "Test",
  "username" : "username",
  "email" : "user@mail.com",
  "password" : "123456",
  "dob" : "2023-05-01",
  "blood" : "AB-",
  "avatar" : "avatar.jpg",
  "id_nr" : "123456789",
  "birth_hospital" : "מאיר",
  "birth_place" : "רחובות",
  "heb_family" : "פייבל",
  "eng_name" : "User",
  "eng_family" : "name",
  "phone" : "0987656766",
  "gender" : 1,
  "login" : "1",
  "former_family" : null,
  "former_eng_family" : null,
  "map" : null
}

### Post LOGIN
POST http://10.10.100.10:3000/users/login
content-type: application/json

{
    "email": "dorfbl@gmail.com",
    "password": "Dor21940"
}


### Show one
GET http://10.10.100.10:3000/users/4


### Delete
DELETE http://10.10.100.10:3000/users/1

### Update
PUT http://10.10.100.10:3000/users/1
content-type: application/json

{
    "name": "Yan"
}